#version 450
#extension GL_EXT_shader_16bit_storage : require
#extension GL_GOOGLE_include_directive : enable
#include "common.inc"

layout(local_size_x = 256) in;

layout(set = 0, binding = 0) buffer OutBuf { float o[]; };
layout(set = 0, binding = 1) readonly buffer WBuf { uint16_t w[]; };

layout(push_constant) uniform PC {
    int id;
    int dim;
} pc;

void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (int(i) >= pc.dim) return;
    o[i] = f16_to_f32(uint(w[uint(pc.id) * uint(pc.dim) + i]));
}
